version: '3.8'
                                      # Template_database
services:
  template_database:                  # Docker: Host name/address
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=template-user   # Docker: Username
      - POSTGRES_PASSWORD=Tb2024cP    # Docker: Pasword
      - POSTGRES_DB=template-db       # Docker: Maitenance database
    ports:
      - "5432:5432"                   # Docker: Port
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
 
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=template.user@email.com
      - PGADMIN_DEFAULT_PASSWORD=Tb2024cP
    ports: 
      - "5052:80"   # Correct port mapping for pgAdmin
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
 
volumes:
  database-data:
  pgadmin:

  # This file is used to set up the local servers in docker on your PC